# Note: this requires the redis operator from
# https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml
# to be installed
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: queue-store
spec:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
---
# We don't need failover, so set up Service pointing directly to the Redis instance.
# It appears that machinery might also not support the sentinel library
apiVersion: v1
kind: Service
metadata:
  name: simple-redis
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: redis
    redisfailovers.databases.spotahome.com/name: queue-store
  ports:
  - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
spec:
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
      - name: manager
        image: "ko://github.com/evankanderson/knative-async-poc/cmd/task-manager"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: BROKER
            # value: redis://rfs-queue-store:26379
            value: redis://simple-redis:6379
          - name: REDIS_MASTER_NAME
            value: mymaster
          - name: RESULT_BACKEND
            # value: redis://rfs-queue-store:26379
            value: redis://simple-redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: queue-server
spec:
  selector:
    app: task-manager
  ports:
  - port: 80
    targetPort: 80
